Solved
WelcomeDev/Simpl_Java pull request #5
Opened 2021-06-23 08:57 UTC by WelcomeDev

2021-06-24 23:59 UTC, progressicu requested changes
Доп. комменты:

* Почему Runner в папке controller?
* название Runner не отражает сути 
* Убери ToString везде - это лишний код, который полезного в данном случае ничего не делает
* CalculationController 
	- поле должно быть final, чтобы заработала аннотация RequiredArgsConstructor. 
	- BufferedReader в try with resources.
	- DataValidation.validate итак выдает boolean, зачем ты еще раз проверяешь ==false?
	- когда exception - пишем в лог
	- int execute(String name, int[] data) у тебя вызывается только для тестов - плохо, лишний код, не должно быть так. В тестах вызываются только рабочие методы, в твоём случае это должно быть только start. Остальные методы должны быть private
* Переименуй ToArrayParser. Можно какой-нибудь ArrayUtil с методом parseFromString(String)
* И вообще, можно было в парсере сразу возвращать List<Integer>, тогда в калькуляторах тебе не нужны было выполнять лишние действия
* В AbstractCalculation зачем ты из чисел собираешь строку. Она у тебя уже есть, просто передай как параметр, если надо. Но а вообще она тебе не нужно, т.к. нигде не используешь
* В тестах убери (classes = Program.class), если без этого у тебя не работает, значит что-то у тебя неправильно

2021-06-24 23:59 UTC, progressicu commented on src/main/java/calculations/controller/Runner.java
> +    @Autowired
Так не нужно делать. Нужно было сделать поле private final и повешать аннотацию `@RequiredArgConstructor`

2021-06-24 23:59 UTC, progressicu commented on src/test/java/testing/Spring/ControllerTest.java
>          else{
Логику убрать в тестах

2021-06-24 23:59 UTC, progressicu commented on src/test/java/testing/calculations/MaxCalculatorTest.java
> +        Calculation calculator = new MaxCalculator();
А если будет много тестовых кейсов будешь каждый раз создавать? Выноси в поле тестового класса и всё

2021-06-24 23:59 UTC, progressicu commented on src/test/java/testing/calculations/MaxCalculatorTest.java
> +
Нужны комменты //Arrange, //Act, //Assert

2021-06-24 23:59 UTC, progressicu commented on src/test/java/testing/calculations/MaxCalculatorTest.java
> +        calculator.setSource(data);
Зачем вы устанавливаете поле бина? Получается, что он тогда хранит состояние, чего не должно быть. Почему нельзя данный массив передать в execute() и сразу получить вывод. Меньше кода -> меньше проблем

2021-06-25 02:21 UTC, WelcomeDev commented
Как удобнее делать ПР по отношению к предыдущему?
 т.е. только то, что изменилось, или по отношению к main - вообще все, что сделал?

2021-06-25 04:27 UTC, WelcomeDev commented
> * В тестах убери (classes = Program.class), если без этого у тебя не работает, значит что-то у тебя неправильно

Исправил, но все работало правильно. 
Просто название стартового файла не совпадало с названием проекта, поэтому без аргумента в аннотации тест его не находил

2021-06-25 04:58 UTC, merged

2021-06-25 05:26 UTC, progressicu commented
> > * В тестах убери (classes = Program.class), если без этого у тебя не работает, значит что-то у тебя неправильно
> 
> Исправил, но все работало правильно.
> Просто название стартового файла не совпадало с названием проекта, поэтому без аргумента в аннотации тест его не находил

Ну spring вообще не ориентируется на названия файлов. Возможно не там лежал, тогда да

2021-06-25 05:31 UTC, progressicu commented
> Как удобнее делать ПР по отношению к предыдущему?
> т.е. только то, что изменилось, или по отношению к main - вообще все, что сделал?

Если я правильно понял сообщение, то вот:
То, что изменилось. Т.е. ты сделал feature1, мы посмотрели, ты слил в dev. Потом создаешь ветку feature2 из ветки dev, что-то делаешь, потом пр. Т.к. ты feature2 из ветки dev создал, то там будут все изменения и из feature1, соответственно они не будут показываться, что там нам и нужно.

Просто я не видел твой код, но захотел посмотреть некоторые вещи, которых нет в пр. Я сам залез и посмотрел, если что отписал, т.к. это не твоя забота, что я что-то не понял/возникли сомнения/еще что-то, твоя задача сделать задачу