Исправление комментариев
WelcomeDev/Simpl_Java pull request #6
Opened 2021-06-25 05:02 UTC by WelcomeDev

2021-07-04 07:56 UTC, progressicu requested changes

2021-07-04 07:56 UTC, progressicu commented on pom.xml
> +            <groupId>org.springframework</groupId>
А для чего это? Тоже самое есть в spring-boot-starter-web

2021-07-04 07:56 UTC, progressicu commented on pom.xml
> +            <groupId>com.google.code.gson</groupId>
И для чего? 
В spring уже есть зависимости для работы с json и прочим - jackson. ObjectMapper используй для преобразования

2021-07-04 07:56 UTC, progressicu commented on src/main/java/calculations/actions/allexecutor/imp/AllCommandExecutorAction.java
> +        List<OperationResultDTO> resultDTOS = new ArrayList<>();
Может сначала ты сделаешь все проверки, а потом создашь это?

2021-07-04 07:56 UTC, progressicu commented on src/main/java/calculations/controller/CalculationRestController.java
> +    @PostMapping("/math/calculate")
/math/calculate можно вынести в @RequestMapping на уровне класса

2021-07-04 07:56 UTC, progressicu commented on src/main/java/calculations/actions/particularexecutor/imp/ParticularCommandExecutorAction.java
> +        Calculation calculation = calculationList.stream()
Можно было поступить красивее. 
В конфиге создать бин Map<String, Calculation> calculationByOperationName. Сюда в поле класса поместить этот бин и просто потом здесь calculationByOperationName.get(opName). Что-то такое

2021-07-04 07:56 UTC, progressicu commented on src/main/java/calculations/actions/particularexecutor/imp/ParticularCommandExecutorAction.java
> +        Calculation calculation = calculationList.stream()
Ну и сначала валидация, а потом все действия

2021-07-04 07:56 UTC, progressicu commented on src/main/java/calculations/controller/dto/OperationResultDTO.java
> +@AllArgsConstructor
А вместо всего этого можно было просто @Value

2021-07-04 07:56 UTC, progressicu commented on src/main/java/calculations/controller/exceptionhandler/RestExceptionHandler.java
> +@ControllerAdvice
А можно было `@RestControllerAdvice` и убрать `@ResponseBody` отовсюду

2021-07-04 07:56 UTC, progressicu commented on src/main/java/calculations/model/calculator/CalculationAvailableOperations.java
> +public class CalculationAvailableOperations {
А почему не enum? enum хорошо маппится из запроса, если дело в этом было

2021-07-04 07:56 UTC, progressicu commented on src/test/java/calculations/calculations/AvgCalculatorTest.java
> +        Calculation calc = new AvgCalculator();
Проверяемые классы можно вынести в поле тестового класса, чтобы не засорять методы

2021-07-04 07:56 UTC, progressicu commented on src/test/java/calculations/calculations/AvgCalculatorTest.java
> +        int expected = (int) data.stream()
А ты не мог сразу написать вручную это число? Зачем усложнять тест

2021-07-04 07:56 UTC, progressicu commented on src/test/java/calculations/integration/PostBodySumCalcRestCtrlTest.java
> +public class PostBodySumCalcRestCtrlTest extends BaseOperationCalcRestCtrlTest {
Так и не понял зачем наследоваться надо было

2021-07-04 07:56 UTC, progressicu commented on src/test/java/calculations/integration/PostBodySumCalcRestCtrlTest.java
> +        MvcResult result = resultActions.andExpect(
В act можно сразу проверить статус и вернуть только тело запроса, т.к. эти пару строк больше усложняют тест

2021-07-04 07:56 UTC, progressicu commented on src/test/java/calculations/integration/PostBodySumCalcRestCtrlTest.java
> +        Gson gson = new Gson();
Через ObjectMapper давай

2021-07-05 01:07 UTC, WelcomeDev commented on src/main/java/calculations/model/calculator/CalculationAvailableOperations.java
> +public class CalculationAvailableOperations {
Нет, сделано было для того, чтобы имена операций не были разбросаны по всей проге. 
Но со стрингом отличное замечание, не подумал об этом, потому что в C# нет Enum из string

2021-07-05 01:08 UTC, WelcomeDev commented on src/test/java/calculations/integration/PostBodySumCalcRestCtrlTest.java
> +public class PostBodySumCalcRestCtrlTest extends BaseOperationCalcRestCtrlTest {
Изначально хотел написать тесты под каждый из запросов sum/avg/min/max, но потом забил
А проверки на длину строки и что-то еще там одинаковые

2021-07-05 01:22 UTC, WelcomeDev commented on pom.xml
> +            <groupId>org.springframework</groupId>
Без него не могу указать MediaType при создании пост запроса через MockMvcRequestBuilders

2021-07-05 01:37 UTC, WelcomeDev commented on src/test/java/calculations/integration/PostBodySumCalcRestCtrlTest.java
> +        MvcResult result = resultActions.andExpect(
По-моему, так только читаемость ухудшается... Но ок

2021-07-05 01:44 UTC, merged

2021-07-05 03:28 UTC, progressicu commented on pom.xml
> +            <groupId>org.springframework</groupId>
Это я к тому, что данная зависимость и так уже у тебя должна [быть](https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-web/2.5.2) (внизу указаны скомпилированные зависимости)

2021-07-05 03:28 UTC, progressicu commented on src/main/java/calculations/model/calculator/CalculationAvailableOperations.java
> +public class CalculationAvailableOperations {
Так тебе строки и не нужны в принципе в данном случае. Просто что-то типа `enum CalculationOperations {SUM, AVG, MIN, MAX}` и всё

2021-07-05 03:28 UTC, progressicu commented on src/test/java/calculations/integration/PostBodySumCalcRestCtrlTest.java
> +        MvcResult result = resultActions.andExpect(
Улучшится, если правильно всё обернуть/создать доп. метод. Если мы делаем одно и тоже каждый раз, то наверное можно как-то это упростить.
Суть такая, что если мы будем делать так, то лишние строки появляются. А можно сделать что-то подобное, как ниже скрин, тогда читаемость улучшается. Можешь даже эту библиотеку взять, чтобы не придумывать своё. Ну или вообще написать через webTestClient
![image](https://user-images.githubusercontent.com/48092349/124412702-6f778680-dd92-11eb-9537-794258d88e1b.png)

2021-07-05 03:28 UTC, progressicu commented on src/test/java/calculations/integration/PostBodySumCalcRestCtrlTest.java
> +        MvcResult result = resultActions.andExpect(
Просто через mockMvc давно никто не делает, много лишнего. Я к этому вёл. 
Ну или можно сделать как-то так
![image](https://user-images.githubusercontent.com/48092349/124413830-c4b49780-dd94-11eb-87a3-8ed0dd3335a8.png)
Как по мне, так читаемее

2021-07-05 03:32 UTC, progressicu commented on src/test/java/calculations/integration/PostBodySumCalcRestCtrlTest.java
> +public class PostBodySumCalcRestCtrlTest extends BaseOperationCalcRestCtrlTest {
Ну смотри.
Мы же знаем, что если одна из этих проверок не пройдет в базовом классе, то все тесты не пройдут и в дочерних. Т.е. получается, что мы устраиваем лишнюю проверку для того, что и так уже проверено. Т.е. так можно было сделать на одной операции, а на остальных проверить только greenway

2021-07-05 03:40 UTC, progressicu commented on src/test/java/calculations/integration/PostBodySumCalcRestCtrlTest.java
> +        MvcResult result = resultActions.andExpect(
Вот кстати [пример](https://github.com/MV-shallow/NumberStats/pull/4/files#diff-77a2e4e1fb2a691cef24ca1b1f5ce7ffe919bbaf9972b3d5a59fb3570277913fR168) тоже нормальный